service: esc-geo-api

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  memorySize: 512
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
      Resource:
        - Fn::Join:
            - ":"
            - - arn:aws:lambda
              - Ref: AWS::Region
              - Ref: AWS::AccountId
              - function:${self:service}-${opt:stage, self:provider.stage}-*

  stage: dev
  region: eu-west-1

plugins:
  - serverless-plugin-warmup

functions:
  fetchLocationData:
    handler: handler.fetchLocationData
    timeout: 10
    warmup: true
    events:
      - http:
          path: location
          method: get
          cors: true

custom:
  warmup:
    officeHoursWarmer:
      enabled: true
      #events:
      #  - schedule: cron(0/5 8-17 ? * MON-FRI *)
      concurrency: 2
    outOfOfficeHoursWarmer:
      enabled: true
      events:
       # - schedule: cron(0/10 * * * ? *)
       # - schedule: cron(0/10 * ? * MON-FRI *)
       # - schedule: cron(0/10 * ? * SAT-SUN *)
       # - schedule: cron(0/10 8-17 ? * MON-FRI *)
       # - schedule: cron(0/10 18-23 ? * MON-FRI *)
       # - schedule: cron(0/10 * ? * SAT-SUN *)
      concurrency: 1
    testWarmer:
      enabled: false

resources:
    Description: Serverless MaxMind GeoIP Stack
